jdbc:
  derby:
    jdbcUrl: jdbc:derby:target/demodb;create=true
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    maximumPoolSize: 1
    minimumIdle: 1

cayenne:
  datasource: derby
  createSchema: true
